INSERT INTO personas (name, title, archetype, industry, description, responsibilities, concerns, quotes, decision_criteria, created_by, created_at, updated_at) VALUES
('Head of Open Banking', 'Head of Open Banking / Open Finance', 'The Liability Sentinel', 'Financial Institutions', 'Deeply concerned with systemic risks and operational liabilities introduced by third-party access in the expanding open finance ecosystem.', 'Managing open banking/finance strategy, third-party risk oversight, regulatory compliance', '["Third-party risk and liability exposure","Unregulated access chains beyond visibility","Brand damage from third-party breaches","Operational blind spots in risk registers","Scaling without safety as open finance expands"]', '["We carry the lion share of liability for fraud and data breach, but don''t control the risk.","This should be on the risk register.","We''re like frogs in a pan… we don''t know when the heat will reach boiling."]', '["Risk mitigation","Liability frameworks","Third-party monitoring","Regulatory alignment"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),

('Chief Risk Officer', 'Chief Risk Officer', 'The Watchtower', 'Financial Institutions', 'Views the open finance ecosystem through a systemic lens — concerned with strategic, reputational, and regulatory risk amplification.', 'Enterprise risk management, regulatory risk, operational resilience', '["Systemic risk amplification from opaque provider chains","Unbalanced liability and risk transfer failure","Visibility gaps and intelligence silos","Governance and accreditation deficiencies","Trust erosion and investment deterrence"]', '["Third-party provider risk isn''t theoretical — it''s systemic.","Scaling the current approach will simply embed unbalanced liability.","Open finance cannot scale on a liability model that writes blank cheques."]', '["Systemic risk reduction","Proportional liability","Real-time monitoring","Governance standards"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),

('CISO', 'Chief Information Security Officer', 'The Perimeter Guardian', 'Financial Institutions', 'Laser-focused on the integrity, resilience, and visibility of the institution''s digital perimeter as open banking scales.', 'Cybersecurity strategy, perimeter defence, threat intelligence, incident response', '["Expanded attack surface from unregulated access chains","Mobile app vulnerabilities exposing hardcoded secrets","Lack of real-time threat intelligence","Data breach risk from aggregated open finance data","Delayed detection and containment of breaches"]', '["Beyond the perimeter of regulation lies a blind spot for cybercrime.","When identity gatekeepers become vectors of fraud, credibility collapses.","Access is too easy to give, and too hard to revoke."]', '["Perimeter integrity","Real-time alerting","Dynamic accreditation","Insurance-backed risk transfer"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),

('Head of Innovation', 'Head of Innovation', 'The Fragile Futurist', 'Financial Institutions', 'Excited about open finance potential but wary of structural risks that could derail innovation, erode trust, and stall adoption.', 'Innovation strategy, new product development, partnership evaluation', '["Innovation at risk from ecosystem fragility","Third-party risk as a hidden innovation killer","Governance gaps preventing confident scaling","Consumer trust erosion undermining data-driven innovation"]', '["If consumers opt out, the open finance ecosystem simply loses its purpose.","Third-party provider risk isn''t theoretical — it''s systemic."]', '["Innovation enablement","Trust preservation","Scalable governance","Consumer confidence"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),

('Aggregator CEO', 'Founder / CEO', 'The Growth Architect', 'Aggregators', 'Focused on scaling the aggregation business while managing the increasing regulatory and security expectations.', 'Company strategy, fundraising, market positioning, regulatory relationships', '["Regulatory uncertainty dampening growth","Liability exposure from downstream providers","Reputational risk from partner breaches","Scaling costs of compliance"]', '["We need to prove we are trustworthy before regulators decide for us."]', '["Market growth","Regulatory positioning","Trust building","Scalable compliance"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),

('TPP CEO', 'Founder / CEO', 'The Access Pioneer', 'Third-Party Providers', 'Building products that leverage open banking APIs, focused on market access and regulatory compliance.', 'Product strategy, market entry, API partnerships, regulatory compliance', '["API access reliability and uptime","Regulatory burden disproportionate to size","Bank resistance to third-party access","Consumer trust in sharing financial data"]', '["Banks see us as a risk, but we see ourselves as the innovation layer."]', '["API reliability","Regulatory compliance","Bank partnerships","Consumer adoption"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000);
