-- Re-seed personas from ICPs draft V0.1.docx
-- Updates existing 6, adds 10 new ones. Preserves IDs referenced by scorecards.

-- Delete personas NOT referenced by scorecards (safe to remove)
DELETE FROM personas WHERE id NOT IN (SELECT DISTINCT persona_id FROM scorecards);

-- Update existing referenced personas with correct document content
UPDATE personas SET
  archetype = 'The Liability Sentinel',
  description = 'Deeply concerned with systemic risks and operational liabilities introduced by third-party access in the expanding open finance ecosystem.',
  responsibilities = 'Managing third-party risk exposure, ensuring regulatory compliance for open banking/finance, overseeing liability frameworks',
  concerns = '["Third-party risk and liability exposure: unregulated access chains, unclear insurance coverage, brand damage from breaches","Operational blind spots and risk register gaps: no real-time monitoring, fragmented intelligence, risk register urgency","Scaling without safety: open finance expansion growing risk exponentially, bandwidth constraints","Governance gaps and lack of proportional accountability: blank cheque liability, no traceable accountability","Strategic imperative to act: unchecked risk dampens innovation, need for industry-led solutions"]',
  quotes = '["We carry the lion''s share of liability for fraud and data breach, but don''t control the risk.","This should be on the risk register. It''s not a question of if, but when.","We''re like frogs in a pan… we don''t know when the heat will reach boiling.","We need to get a handle on this before we dive into the Open finance world…"]',
  decision_criteria = '["Proportional liability framework","Real-time third-party monitoring","Scalable federated defences","Entity-level accountability with IDs, timestamps, risk scores"]',
  updated_at = strftime('%s','now') * 1000
WHERE name = 'Head of Open Banking';

UPDATE personas SET
  archetype = 'The Fragile Futurist',
  description = 'Excited about open finance''s transformative potential but wary of structural risks that could derail innovation, erode trust, and stall adoption.',
  responsibilities = 'Driving open finance innovation, evaluating third-party partnerships, scaling new products, managing innovation risk',
  concerns = '["Innovation at risk: scaling without safety makes innovation brittle, trust erosion threatens consumer confidence","Third-party risk as a hidden innovation killer: unregulated access chains, contagion potential from weak links","Governance gaps and lack of ecosystem resilience: no dynamic accreditation, operational fragility","Investment deterrence and strategic hesitation: unbalanced liability chills innovation appetite, no visibility into ecosystem health","Call for industry-led resilience to unlock innovation"]',
  quotes = '["If consumers opt out, the open finance ecosystem simply loses its purpose.","Third-party provider risk isn''t theoretical — it''s systemic.","Poor behaviour proliferates unchecked, undermining safe expansion.","Participants can''t assess whether the ecosystem is healthy and worthy of investment.","To unlock the full value of open finance, we must shift from distributed risks to federated resilience."]',
  decision_criteria = '["De-risked innovation through federated resilience","Consumer trust preservation","Scalable partnership frameworks with dynamic accreditation","Insurance-backed accountability aligning incentives"]',
  updated_at = strftime('%s','now') * 1000
WHERE name = 'Head of Innovation';

-- Insert all personas (existing + new) using INSERT OR IGNORE to skip duplicates
INSERT OR IGNORE INTO personas (name, title, archetype, industry, description, responsibilities, concerns, quotes, decision_criteria, created_by, created_at, updated_at) VALUES
('Chief Risk Officer', 'Chief Risk Officer', 'The Watchtower', 'Financial Institution', 'Views the open finance ecosystem through a systemic lens — concerned with strategic, reputational, and regulatory risk amplification.', 'Strategic risk oversight, regulatory risk management, systemic risk assessment, liability framework governance', '["Systemic risk amplification: opaque risk chains, contagion potential from single weak links","Unbalanced liability and risk transfer failure: blank cheque exposure, insurance ambiguity","Visibility gaps and intelligence silos: fragmented monitoring, reactive posture","Governance and accreditation deficiencies: no unified standards, no dynamic risk scoring","Strategic risk to trust, investment, and ecosystem growth"]', '["Third-party provider risk isn''t theoretical — it''s systemic.","Scaling the current approach will simply embed unbalanced liability in the open finance ecosystem.","Few are tracing incidents back to third-party access… the sector remains blind to systemic fragility.","Without standardised approaches, poor behaviour proliferates unchecked.","Open finance cannot scale on a liability model that writes blank cheques."]', '["Systemic risk reduction across provider chains","Proportional liability with insurance-backed transfer","Real-time risk scoring and dynamic accreditation","Unified governance standards across regulated and unregulated entities"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('CISO', 'Chief Information Security Officer', 'The Perimeter Guardian', 'Financial Institution', 'Laser-focused on the integrity, resilience, and visibility of the institution''s digital perimeter as open banking scales.', 'Digital perimeter security, threat intelligence, incident response, security architecture for open APIs', '["Expanded attack surface and ecosystem fragility: unregulated access chains, mobile app vulnerabilities, third-party impersonation","Lack of real-time threat intelligence and monitoring: no unified accreditation or scoring, fragmented visibility","Data breach risk and identity theft exposure: high-value targets, delayed detection and containment","Governance gaps and accountability failures: no traceable liability, reactive revocation model","Strategic imperative for federated resilience: dynamic accreditation, real-time alerting, insurance-backed risk transfer"]', '["Beyond the perimeter of regulation lies a blind spot for cybercrime.","Cybercrime patterns go undetected until too late.","When identity gatekeepers become vectors of fraud, credibility collapses.","Access is too easy to give, and too hard to revoke.","Open finance promises innovation, but without resilience, openness becomes fragility."]', '["Dynamic accreditation tied to real-time behaviour","Pooled threat intelligence across ecosystem","Entity-level traceability and containment protocols","Insurance-backed risk transfer to party introducing risk"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('Aggregator CEO', 'Founder / CEO', 'The Ecosystem Conduit', 'Aggregator', 'As connective tissue in the open finance ecosystem, aggregators are both enablers of innovation and lightning rods for liability.', 'Strategic leadership, ecosystem partnerships, regulatory navigation, risk governance', '["Downstream risk without upstream control: opaque third-party chains, blame without agency","Insurance ambiguity and liability exposure: PII coverage gaps, unbalanced liability","Operational drag and compliance overhead: rising compliance costs, manual processes","Trust fragility and brand risk: reputational exposure from downstream actors, loss of legitimacy","Strategic opportunity: accreditation as a differentiator"]', '["We''re held accountable for risks we can''t see and actors we don''t control.","We lack clarity on whether we''re covered — or just exposed.","As we scale, our compliance costs rise too. Invela offers a way to contain those costs while boosting operational efficiency.","If we''re compromised, data flows fragment — and trust erodes.","Accreditation isn''t just compliance — it''s a competitive edge."]', '["Downstream visibility and control","Clear insurance and liability framework","Scalable compliance automation","Dynamic accreditation as trust differentiator"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('Aggregator CRO', 'Chief Revenue Officer', 'The Trust-Reliant Rainmaker', 'Aggregator', 'High-stakes balancing act: driving growth and monetization while managing reputational exposure, compliance drag, and partner trust.', 'Revenue growth, partner acquisition, commercial strategy, market positioning', '["Revenue risk from ecosystem fragility: trust erosion equals revenue erosion, downstream failures have upstream consequences","Compliance overhead and margin compression: rising costs without proportional revenue, manual risk management","Brand risk and commercial credibility: reputational exposure from breaches, loss of preferred partner status","Lack of differentiated trust signals: no industry-wide trust mark, limited visibility into ecosystem health","Strategic opportunity: risk management as a revenue enabler"]', '["We''re blamed for risks we didn''t create — but we still pay the price.","Invela offers a way to contain those costs while boosting operational efficiency.","If we''re compromised, trust erodes — and commercial traction follows.","We need to show — not just say — that we''re the safest way to scale.","Operational resilience isn''t just risk mitigation — it''s a growth strategy."]', '["Trust signals that accelerate sales cycles","Reduced compliance overhead preserving margins","Differentiated risk posture vs competitors","Insurance-backed accountability reducing partner friction"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('Aggregator COO', 'Chief Operating Officer', 'The Blind-folded Operator', 'Aggregator', 'Pressing operational paradox: aggregators are structurally essential yet exposed to cascading risks they can''t fully control.', 'Operational efficiency, compliance operations, incident response, integration management', '["Operational exposure without real-time control: opaque downstream chains, no real-time alerting","Systemic risk and fragility: single point of failure potential, cybercrime blind spots","Compliance burden and cost containment: rising regulatory expectations, fragmented manual processes","Liability ambiguity and insurance gaps: unclear indemnity coverage, disproportionate blame","Strategic opportunity: operational resilience as differentiator"]', '["We''re the connective tissue — but we''re flying blind.","Poor behaviour proliferates unchecked, and we''re left holding the bag.","Invela offers a way to contain those costs while boosting operational efficiency.","We''re exposed to risk without the tools or frameworks to manage it.","Operational resilience isn''t just protection — it''s a platform for growth."]', '["Real-time operational visibility and alerting","Standardised compliance frameworks that scale","Clear liability boundaries with insurance backing","Dynamic accreditation tied to behaviour"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('TPP CEO', 'Founder / CEO', 'The Exposed Innovator', 'Third Party Provider', 'Faces existential threats and strategic opportunities. As innovators driving the open finance ecosystem forward, TPPs are essential but exposed.', 'Strategic vision, fundraising, regulatory positioning, ecosystem partnerships', '["Operational vulnerability and limited defensibility: resource constraints, malicious compromise risk","Liability ambiguity and insurance gaps: unclear indemnity coverage, disproportionate exposure","Trust deficit and market access risk: lack of accreditation, risk of ecosystem exclusion","Reputational fragility and ecosystem dependence: brand risk from single incident, constant credibility scrutiny","Strategic opportunity: resilience as differentiator"]', '["We run the risk of being compromised without the pocket to defend ourselves.","We''re exposed to cascading liability without clarity on coverage.","Accreditation as an industry trust mark aligns perfectly with our values.","We intend to lead the conversation on quality, not just follow it.","Operational resilience isn''t just protection — it''s a platform for growth and legitimacy."]', '["Affordable defensive security infrastructure","Clear liability and insurance framework","Industry trust mark for market access","Proportionate accountability mechanisms"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('TPP CRO', 'Chief Revenue Officer', 'The Risky Challenger', 'Third Party Provider', 'Navigates a high-stakes commercial landscape: open finance offers explosive growth but only if trust and resilience are secured.', 'Revenue growth, bank partnerships, market access, commercial positioning', '["Revenue risk from trust deficits: market access fragility, brand suspicion","Sales friction and partnership barriers: due diligence drag, reactive risk posture","Liability ambiguity and commercial exposure: insurance uncertainty, unbalanced accountability","Reputational fragility and growth constraints: one breach equals ecosystem exclusion, no trust mark","Strategic opportunity: resilience as a revenue enabler"]', '["We need to be seen as safe, not just smart.","We''re losing deals not because we''re weak — but because we''re invisible.","We carry risk without the tools to manage or transfer it.","We need a way to prove we''re not just compliant — we''re credible.","Operational resilience isn''t just protection — it''s a commercial advantage."]', '["Accreditation that unlocks market access","Reduced due diligence friction with partners","Visible trust signals for sales conversations","Insurance-backed accountability reducing commercial risk"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('TPP COO', 'Chief Operating Officer', 'The Overstretched Builder', 'Third Party Provider', 'Faces operational tension: TPPs are engines of innovation yet face structural vulnerabilities and rising partner expectations.', 'Operations management, compliance, security infrastructure, integration delivery', '["Operational fragility and limited defensibility: security exposure, no real-time monitoring","Cascading risk and ecosystem dependence: downstream risk with upstream blame, contagion potential","Compliance burden and operational overhead: manual onboarding and due diligence, unclear insurance","Lack of trust infrastructure and market legitimacy: no dynamic accreditation, risk of access exclusion","Strategic opportunity: operational resilience as differentiator"]', '["We''re expected to be secure — but we''re not equipped to prove it or act fast.","We''re part of a chain — but we''re treated like the anchor when things go wrong.","We''re spending more time proving we''re safe than building what''s next.","We need to show — not just say — that we''re trustworthy.","Resilience isn''t just protection — it''s permission to grow."]', '["Scalable security infrastructure within budget","Standardised accreditation reducing duplicative checks","Real-time monitoring and incident response","Trust mark enabling ecosystem access"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('Consumer', 'End User', 'The Unseen Stakeholder', 'Consumer', 'Cares about personal data safety, fraud protection, and confidence in who holds their financial information.', 'Managing personal finances, consenting to data sharing, monitoring for fraud', '["Personal data safety and identity theft risk","Fraud protection and financial loss prevention","Lack of visibility into who accesses their data","Inability to easily revoke access or track data flows","Trust in digital financial services"]', '["I don''t know who has my data or what they do with it.","If something goes wrong, I don''t know who to blame."]', '["Invisible real-time protection","Proactive risk exclusion","Frictionless consent management","Trust as default, not burden"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('Industry Body Leader', 'Executive Director', 'The Sector Steward', 'Industry Body', 'Cares about sector-wide resilience, reputational integrity, and member alignment with policy and innovation goals.', 'Sector advocacy, member coordination, policy engagement, standards promotion', '["Sector-wide resilience and systemic risk","Reputational integrity of the industry","Member alignment with evolving policy and regulation","Balancing innovation with safety across diverse membership"]', '["The sector needs coordinated defences, not fragmented responses.","Our members need frameworks that scale without duplicative compliance."]', '["Scalable industry-led defence framework","Reduced systemic risk across members","Proactive policy implementation partnership","Standards that don''t stifle innovation"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('Regulator', 'Senior Policy Director', 'The Mandate Enforcer', 'Regulator', 'Cares about consumer protection, market integrity, and enforceable liability frameworks within sectoral remits.', 'Policy development, enforcement, market oversight, consumer protection mandates', '["Consumer protection in open ecosystems","Market integrity and systemic stability","Enforceable liability frameworks across regulated and unregulated actors","Visibility and traceability of risk across data chains"]', '["We need visibility without overreach.","Proportional accountability must be the foundation of open finance governance."]', '["Federated resilience complementing regulatory intent","Proportional accountability mechanisms","Visibility and traceability across providers","Risk transfer mechanisms regulators can endorse"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('Investor', 'Managing Partner', 'The Category Kingmaker', 'Investor', 'Seeks scalable market opportunity, defensible category leadership, and clear pathways to monetization and regulatory alignment.', 'Investment evaluation, portfolio management, market analysis, category thesis development', '["Scalable market opportunity in open finance risk management","Defensible category leadership and first-mover advantage","Clear pathways to monetization and regulatory alignment","Systemic problem-solving with cross-sector applicability","Regulatory tailwinds and platform play potential"]', '["This is a category-defining opportunity in open finance risk infrastructure.","Three lines of defence — accreditation, monitoring, insurance — create a flywheel.","This isn''t just a product — it''s a platform play with regulatory tailwinds."]', '["Category-defining positioning","Flywheel of trust, adoption, and resilience","Cross-sector applicability","First-mover advantage in federated risk intelligence"]', 'system', strftime('%s','now') * 1000, strftime('%s','now') * 1000);
